### ISSUE TITLE
Output from get not displaying what outputs from the terminal

### ISSUE THREAD

**Issue by JacobJT** [RIAEvangelist/node-cmd#36]
I have a simple script I'm running that performs some pre-deploy tasks, and then deploys my built to Elastic Beanstalk on AWS.

```
var cmd = require('node-cmd');
var util = require('gulp-util');
var env = util.env.MY_FLAG;

console.log("Running script");

try {
    cmd.get(
	    `gulp MY_GULP_COMMAND --MY_FLAG ${MY_FLAG}`,
	    results => { 
			console.log(results);
			cmd.get(
				`eb deploy MY_EB_ENVIRONMENT`,
				results => { console.log(results); }
			)
		}
	);
} catch (e) {
    console.log(JSON.stringify(e))
}
```
This is the output of running my script:

```
Running script
null
{ Error: Command failed: eb deploy MY_EB_ENVIRONMENT

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
  killed: false,
  code: 4,
  signal: null,
  cmd: 'eb deploy MY_EB_ENVIRONMENT' }
```

However, here's the output of running the commands in the terminal specifically:
`gulp MY_GULP_COMMAND --MY_FLAG ${MY_FLAG}`

```
[11:19:04] Using gulpfile MY_GULPFILE.js
[11:19:04] Starting 'MY_GULP_COMMAND'...
[11:19:04] Finished 'MY_GULP_COMMAND' after 64 ms
```
`eb deploy MY_EB_ENVIRONMENT`

```
Creating application version archive "APP_ARCHIVE".
Uploading: [##################################################] 100% Done...
ERROR: ServiceError - You cannot have more than 1000 Application Versions. Either remove some Application Versions or request a limit increase.
```

For some reason, no output at all is being displayed from the gulp command, and not the correct output from the eb deploy command. Here I was experiencing a deploy error and couldn't really tell what it was without having to run the commands myself.

**Comment by RIAEvangelist** [comment]
looks like you are logging an empty error?

**Comment by jrichardsz** [comment]
If anyone needs, I solved following https://stackoverflow.com/a/74408421/3957754
